### PR TITLE
Image addition for tests + URL modifications

### PR DESCRIPTION
**Pull request by tjslezak**
* Added test image for previously added GalileoSSI instrument model
* Added Voyager NAC image used in upcoming instrument model test
* Modified Mercury DIS NAC+WAC filenames to reflect recent PDS changes

### CODE REVIEW

**Comment by percurnicus** [comment]
Do any of the new images have detached labels?

**Comment by percurnicus** [comment]
Don't make any changes now, but I suspect there will be merge conflicts with #12. It will be clearer when I make a release branch

**Comment by percurnicus** [comment]
@tjslezak Can you fix the merge conflicts?

**Comment by tjslezak** [comment]
@pbvarga1 Yeah, I’ll take care of it.

The Galileo SSI image (6413r.img) has a detached .lbl file under the same path in the same directory. The Voyager NAC image (c16xxxx.imq) label is internal.

**Comment by percurnicus** [comment]
Ok Make sure the label url ends up in the json as well

**Comment by percurnicus** [comment]
Notice you are merging into release-0.4.0 branch, so your conflicts are with that branch, not master

**Comment by percurnicus** [comment]
@tjslezak You having trouble resolving merge conflicts?

**Comment by tjslezak** [comment]
@pbvarga1 Yes.

**Comment by percurnicus** [comment]
Did you add the planetarypy fork as a remote?
(Show me the result of ``git remote -v``)

**Comment by tjslezak** [comment]
local:planetary_test_data tjs$ git remote -v
origin	https://tjslezak@github.com/tjslezak/planetary_test_data.git (fetch)
origin	https://tjslezak@github.com/tjslezak/planetary_test_data.git (push)
upstream	https://github.com/planetarypy/planetary_test_data (fetch)
upstream	https://github.com/planetarypy/planetary_test_data (push)
local:planetary_test_data tjs$

**Comment by tjslezak** [comment]
I started using Atom this week and now my life is over. 
Hopefully you got enough notification emails from me. 
Going back to the instrument models until I get my .git/.gitconfig(s) fixed up.

**Comment by percurnicus** [comment]
ok good. In the future, create an issue/feature branch and push to that branch. Rarely do you want to push to your master branch unless you are updating it to match the upstream master or its a really minor fix (like a dumb spelling error or something - nothing wrong with. This may be tougher since you've been pushing to master...
Ok try this:
```
git pull upstream release-0.4.0
```
Then you should get some merge conflict errors. Fix those in your text editor... I'm not super confident because that's not how you normally do it. If you used a feature branch it would go like this:
```
git checkout master
git pull upstream master
git checkout release-0.4.0
git pull upstream release-0.4.0
git checkout feature_branch
git merge release-0.4.0
```
Go give the first way a try and let me know how that goes

**Comment by percurnicus** [comment]
WAIT!

**Comment by percurnicus** [comment]
Just noticed you have the release branch. Do this:
```
git checkout release-0.4.0
git pull upstream release-0.4.0
git checkout master
git merge release-0.4.0
```
Then fix the merge conflicts that appear. Once done commit the changes and push again

**Comment by tjslezak** [comment]
Ok, those commits didn't include any of what I added/fixed (I stashed my changes and have a copy of the modified files) but now I know where I am! Thanks!

[Atom is still hanging out with me](https://github.com/planetarypy/planetary_test_data/pull/18/commits/ecec1e47edc5385f82fd97516601392846f8b359#diff-c0141a54bd9b45f5d10415618c9eb659). Time to clean house.

**Comment by percurnicus** [comment]
If you can fix everything today, great. But at this point, I suggest storing the changes you want to add the ``data.json`` elsewhere and totally restarting your repo. I'm not going to accept this PR with a bunch of pointless binary files and it is still out of sync with the rest of the release branch. Since your master branch is also not correct it will be very difficult to talk your through how to get it back in sync. Delete your local repo, delete your fork, refork, reclone your fork, add planetarypy as upstream remote, checkout to the release branch, create and checkout to a proper feature branch (make the name obvious to what you are doing, like ``add_products_to_json``), add in those changes to ``data.json`` that you stored, push those changes to origin, and make a new PR. I expect that PR to be up to date with the rest of the release branch and with only one commit making changes to one file ``data.json``. You don't need to fix/add any new tests for adding additional products. I'll let you know if any of the documentation needs to be updated based on your new products. But keep the PR focused just on the new products.

**Comment by percurnicus** [comment]
I'm have no idea why Atom creates random binary files but please never commit them (I have a feeling you ran ``git add .``) This should be your process:
1. Make sure you are on the right branch: ``git branch``
2. Check what files have been changed: ``git status``
3. Check those changes are what you intend to commit: ``git diff file_path.ext``
4. Add *just* the file you checked: ``git add file_path.ext``
5. Run ``git status`` again to make sure the **only** the files ready to commit are in green.
6. Ask yourself, Do I want to commit the files in green? If yes, commit. If no then reset unwanted files and then commit.

**Comment by tjslezak** [comment]
@pbvarga1 Thanks for the rundown and your suggestions. I initially forgot to create a branch (stupid) and then switching to the new release complicated things even more. Considered deleting everything and starting fresh but thought I could eventually make it work. Yeah, exactly what I meant by cleaning house - deleting my local repo/environment entirely and reforking/cloning the current repo. Agreed, definitely close this PR, it provides no contribution besides me demonstrating how to do it wrong. I know what a good PR is, this is a trainwreck. I can be stubborn sometimes, should've dropped that following release-0.4.0. Now I know. Appreciate the help. It's funny how we've traded mentee and mentor roles, I got you in, tricked you with `yes` - now you own the repos. Bravo. 🥇

**Comment by tjslezak** [comment]
Regardless, I want the project to be successful and it will be with beneficial contributions. Be sure to point out any of my mistakes. Will adhere with more care to the contribution guidelines in the future. Again, thanks for your help on this one.

**Comment by percurnicus** [comment]
@tjslezak haha ok, I pushed the release back a week, I think the products you were adding are important and look forward to your new PR!

**Pull request closed without merging**
